### ISSUE TITLE
AsyncStorage is defined at multiple times

### ISSUE THREAD

**Issue by TechSaq** [jayampathiadhikari/react-native-async-storage-listener#4]
You are using @react-native-community/async-storage as a dependency which is deprecated. Almost everyone is using @react-native-async-storage/async-storage and due to this while using your library, it gives an error AsyncStorage is defined at multiple times

**Comment by jayampathiadhikari** [comment]
@TechSaq Thank you for your input. Could you please try the new version? I have changed it to use @react-native-async-storage/async-storage. Please let me know if it works. So that I can close this issue.

**Comment by TechSaq** [comment]
I applied the patch for it in my project but I will revert the patch and will let you know.

**Comment by TechSaq** [comment]
Thanks @jayampathiadhikari , it is working
