### ISSUE TITLE
Add Clear Item 

### ISSUE THREAD

**Issue by dahed92** [jayampathiadhikari/react-native-async-storage-listener#5]
Hi, thanks for this package, but I was wondering why you haven't included the "clear item" method?

**Comment by jayampathiadhikari** [comment]
@dahed92 Hi, I have forgotten to add that method. Do you want it included ?

**Comment by dahed92** [comment]
Yes it would be nice

**Comment by jayampathiadhikari** [comment]
@dahed92 Could you please try the new version and let me know if it works

**Comment by jayampathiadhikari** [comment]
latest version is 1.2.0

**Comment by dahed92** [comment]
> @dahed92 Could you please try the new version and let me know if it works

I tested the StorageListener.cleariIem and everything seems to work fine, thank you very much for your work
